//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SurveyEntities", "SurveyTypeSurveyQuestion", "SurveyType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomerSurvey3.Web.SurveyType), "SurveyQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomerSurvey3.Web.SurveyQuestion), true)]
[assembly: EdmRelationshipAttribute("SurveyEntities", "SurveyInstanceSurveyType", "SurveyInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomerSurvey3.Web.SurveyInstance), "SurveyType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomerSurvey3.Web.SurveyType), true)]
[assembly: EdmRelationshipAttribute("SurveyEntities", "SurveyQuestionSurveyAnswer", "SurveyQuestion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomerSurvey3.Web.SurveyQuestion), "SurveyAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomerSurvey3.Web.SurveyAnswer), true)]
[assembly: EdmRelationshipAttribute("SurveyEntities", "SurveyInstanceSurveyAnswer", "SurveyInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CustomerSurvey3.Web.SurveyInstance), "SurveyAnswer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CustomerSurvey3.Web.SurveyAnswer), true)]

#endregion

namespace CustomerSurvey3.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SurveyEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SurveyEntitiesContainer object using the connection string found in the 'SurveyEntitiesContainer' section of the application configuration file.
        /// </summary>
        public SurveyEntitiesContainer() : base("name=SurveyEntitiesContainer", "SurveyEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SurveyEntitiesContainer object.
        /// </summary>
        public SurveyEntitiesContainer(string connectionString) : base(connectionString, "SurveyEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SurveyEntitiesContainer object.
        /// </summary>
        public SurveyEntitiesContainer(EntityConnection connection) : base(connection, "SurveyEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyType> SurveyTypes
        {
            get
            {
                if ((_SurveyTypes == null))
                {
                    _SurveyTypes = base.CreateObjectSet<SurveyType>("SurveyTypes");
                }
                return _SurveyTypes;
            }
        }
        private ObjectSet<SurveyType> _SurveyTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyQuestion> SurveyQuestions
        {
            get
            {
                if ((_SurveyQuestions == null))
                {
                    _SurveyQuestions = base.CreateObjectSet<SurveyQuestion>("SurveyQuestions");
                }
                return _SurveyQuestions;
            }
        }
        private ObjectSet<SurveyQuestion> _SurveyQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyInstance> SurveyInstances
        {
            get
            {
                if ((_SurveyInstances == null))
                {
                    _SurveyInstances = base.CreateObjectSet<SurveyInstance>("SurveyInstances");
                }
                return _SurveyInstances;
            }
        }
        private ObjectSet<SurveyInstance> _SurveyInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyAnswer> SurveyAnswers
        {
            get
            {
                if ((_SurveyAnswers == null))
                {
                    _SurveyAnswers = base.CreateObjectSet<SurveyAnswer>("SurveyAnswers");
                }
                return _SurveyAnswers;
            }
        }
        private ObjectSet<SurveyAnswer> _SurveyAnswers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lookup> Lookups
        {
            get
            {
                if ((_Lookups == null))
                {
                    _Lookups = base.CreateObjectSet<Lookup>("Lookups");
                }
                return _Lookups;
            }
        }
        private ObjectSet<Lookup> _Lookups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyUser> SurveyUsers
        {
            get
            {
                if ((_SurveyUsers == null))
                {
                    _SurveyUsers = base.CreateObjectSet<SurveyUser>("SurveyUsers");
                }
                return _SurveyUsers;
            }
        }
        private ObjectSet<SurveyUser> _SurveyUsers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyTypes(SurveyType surveyType)
        {
            base.AddObject("SurveyTypes", surveyType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyQuestions(SurveyQuestion surveyQuestion)
        {
            base.AddObject("SurveyQuestions", surveyQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyInstances(SurveyInstance surveyInstance)
        {
            base.AddObject("SurveyInstances", surveyInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyAnswers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyAnswers(SurveyAnswer surveyAnswer)
        {
            base.AddObject("SurveyAnswers", surveyAnswer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lookups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLookups(Lookup lookup)
        {
            base.AddObject("Lookups", lookup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyUsers(SurveyUser surveyUser)
        {
            base.AddObject("SurveyUsers", surveyUser);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="address">No Metadata Documentation available.</param>
        public ObjectResult<FindUHTenant_Result> FindUHTenant(global::System.String name, global::System.String address)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter addressParameter;
            if (address != null)
            {
                addressParameter = new ObjectParameter("Address", address);
            }
            else
            {
                addressParameter = new ObjectParameter("Address", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<FindUHTenant_Result>("FindUHTenant", nameParameter, addressParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="Lookup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lookup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lookup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="order">Initial value of the Order property.</param>
        public static Lookup CreateLookup(global::System.Int32 id, global::System.String type, global::System.String text, global::System.Decimal order)
        {
            Lookup lookup = new Lookup();
            lookup.Id = id;
            lookup.Type = type;
            lookup.Text = text;
            lookup.Order = order;
            return lookup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Decimal _Order;
        partial void OnOrderChanging(global::System.Decimal value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active = true;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UHRef
        {
            get
            {
                return _UHRef;
            }
            set
            {
                OnUHRefChanging(value);
                ReportPropertyChanging("UHRef");
                _UHRef = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UHRef");
                OnUHRefChanged();
            }
        }
        private global::System.String _UHRef;
        partial void OnUHRefChanging(global::System.String value);
        partial void OnUHRefChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="SurveyAnswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyAnswer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyAnswer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="surveyQuestionId">Initial value of the SurveyQuestionId property.</param>
        /// <param name="surveyInstanceId">Initial value of the SurveyInstanceId property.</param>
        public static SurveyAnswer CreateSurveyAnswer(global::System.Int32 id, global::System.String text, global::System.Int32 surveyQuestionId, global::System.Int32 surveyInstanceId)
        {
            SurveyAnswer surveyAnswer = new SurveyAnswer();
            surveyAnswer.Id = id;
            surveyAnswer.Text = text;
            surveyAnswer.SurveyQuestionId = surveyQuestionId;
            surveyAnswer.SurveyInstanceId = surveyInstanceId;
            return surveyAnswer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyQuestionId
        {
            get
            {
                return _SurveyQuestionId;
            }
            set
            {
                OnSurveyQuestionIdChanging(value);
                ReportPropertyChanging("SurveyQuestionId");
                _SurveyQuestionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyQuestionId");
                OnSurveyQuestionIdChanged();
            }
        }
        private global::System.Int32 _SurveyQuestionId;
        partial void OnSurveyQuestionIdChanging(global::System.Int32 value);
        partial void OnSurveyQuestionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyInstanceId
        {
            get
            {
                return _SurveyInstanceId;
            }
            set
            {
                OnSurveyInstanceIdChanging(value);
                ReportPropertyChanging("SurveyInstanceId");
                _SurveyInstanceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyInstanceId");
                OnSurveyInstanceIdChanged();
            }
        }
        private global::System.Int32 _SurveyInstanceId;
        partial void OnSurveyInstanceIdChanging(global::System.Int32 value);
        partial void OnSurveyInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ref
        {
            get
            {
                return _Ref;
            }
            set
            {
                OnRefChanging(value);
                ReportPropertyChanging("Ref");
                _Ref = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ref");
                OnRefChanged();
            }
        }
        private global::System.String _Ref;
        partial void OnRefChanging(global::System.String value);
        partial void OnRefChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyQuestionSurveyAnswer", "SurveyQuestion")]
        public SurveyQuestion SurveyQuestion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyQuestion>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyQuestion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyQuestion>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyQuestion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyQuestion> SurveyQuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyQuestion>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyQuestion>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyInstanceSurveyAnswer", "SurveyInstance")]
        public SurveyInstance SurveyInstance
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyInstance").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyInstance").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyInstance> SurveyInstanceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="SurveyInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyInstance object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="surveyTypeId">Initial value of the SurveyTypeId property.</param>
        public static SurveyInstance CreateSurveyInstance(global::System.Int32 id, global::System.DateTime date, global::System.Int32 surveyTypeId)
        {
            SurveyInstance surveyInstance = new SurveyInstance();
            surveyInstance.Id = id;
            surveyInstance.Date = date;
            surveyInstance.SurveyTypeId = surveyTypeId;
            return surveyInstance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyTypeId
        {
            get
            {
                return _SurveyTypeId;
            }
            set
            {
                OnSurveyTypeIdChanging(value);
                ReportPropertyChanging("SurveyTypeId");
                _SurveyTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyTypeId");
                OnSurveyTypeIdChanged();
            }
        }
        private global::System.Int32 _SurveyTypeId;
        partial void OnSurveyTypeIdChanging(global::System.Int32 value);
        partial void OnSurveyTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UHTenantRef
        {
            get
            {
                return _UHTenantRef;
            }
            set
            {
                OnUHTenantRefChanging(value);
                ReportPropertyChanging("UHTenantRef");
                _UHTenantRef = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UHTenantRef");
                OnUHTenantRefChanged();
            }
        }
        private global::System.String _UHTenantRef;
        partial void OnUHTenantRefChanging(global::System.String value);
        partial void OnUHTenantRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UHPersonNo
        {
            get
            {
                return _UHPersonNo;
            }
            set
            {
                OnUHPersonNoChanging(value);
                ReportPropertyChanging("UHPersonNo");
                _UHPersonNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UHPersonNo");
                OnUHPersonNoChanged();
            }
        }
        private Nullable<global::System.Int32> _UHPersonNo;
        partial void OnUHPersonNoChanging(Nullable<global::System.Int32> value);
        partial void OnUHPersonNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Relationship
        {
            get
            {
                return _Relationship;
            }
            set
            {
                OnRelationshipChanging(value);
                ReportPropertyChanging("Relationship");
                _Relationship = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Relationship");
                OnRelationshipChanged();
            }
        }
        private global::System.String _Relationship;
        partial void OnRelationshipChanging(global::System.String value);
        partial void OnRelationshipChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyInstanceSurveyType", "SurveyType")]
        public SurveyType SurveyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyInstanceSurveyType", "SurveyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyInstanceSurveyType", "SurveyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyType> SurveyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyInstanceSurveyType", "SurveyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyType>("SurveyEntities.SurveyInstanceSurveyType", "SurveyType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyInstanceSurveyAnswer", "SurveyAnswer")]
        public EntityCollection<SurveyAnswer> SurveyAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyAnswer>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyAnswer>("SurveyEntities.SurveyInstanceSurveyAnswer", "SurveyAnswer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="SurveyQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyQuestion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="surveyTypeId">Initial value of the SurveyTypeId property.</param>
        public static SurveyQuestion CreateSurveyQuestion(global::System.Int32 id, global::System.String text, global::System.String type, global::System.Int32 surveyTypeId)
        {
            SurveyQuestion surveyQuestion = new SurveyQuestion();
            surveyQuestion.Id = id;
            surveyQuestion.Text = text;
            surveyQuestion.Type = type;
            surveyQuestion.SurveyTypeId = surveyTypeId;
            return surveyQuestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidationRule
        {
            get
            {
                return _ValidationRule;
            }
            set
            {
                OnValidationRuleChanging(value);
                ReportPropertyChanging("ValidationRule");
                _ValidationRule = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidationRule");
                OnValidationRuleChanged();
            }
        }
        private global::System.String _ValidationRule;
        partial void OnValidationRuleChanging(global::System.String value);
        partial void OnValidationRuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private global::System.Decimal _Order = 0m;
        partial void OnOrderChanging(global::System.Decimal value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyTypeId
        {
            get
            {
                return _SurveyTypeId;
            }
            set
            {
                OnSurveyTypeIdChanging(value);
                ReportPropertyChanging("SurveyTypeId");
                _SurveyTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyTypeId");
                OnSurveyTypeIdChanged();
            }
        }
        private global::System.Int32 _SurveyTypeId;
        partial void OnSurveyTypeIdChanging(global::System.Int32 value);
        partial void OnSurveyTypeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyTypeSurveyQuestion", "SurveyType")]
        public SurveyType SurveyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyType> SurveyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyType>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyType>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyQuestionSurveyAnswer", "SurveyAnswer")]
        public EntityCollection<SurveyAnswer> SurveyAnswers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyAnswer>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyAnswer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyAnswer>("SurveyEntities.SurveyQuestionSurveyAnswer", "SurveyAnswer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="SurveyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static SurveyType CreateSurveyType(global::System.Int32 id, global::System.String name)
        {
            SurveyType surveyType = new SurveyType();
            surveyType.Id = id;
            surveyType.Name = name;
            return surveyType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details = "\'\'";
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active = true;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyTypeSurveyQuestion", "SurveyQuestion")]
        public EntityCollection<SurveyQuestion> SurveyQuestions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyQuestion>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyQuestion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyQuestion>("SurveyEntities.SurveyTypeSurveyQuestion", "SurveyQuestion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SurveyEntities", "SurveyInstanceSurveyType", "SurveyInstance")]
        public EntityCollection<SurveyInstance> SurveyInstances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyType", "SurveyInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyInstance>("SurveyEntities.SurveyInstanceSurveyType", "SurveyInstance", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SurveyEntities", Name="SurveyUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyUser object.
        /// </summary>
        /// <param name="user_name">Initial value of the user_name property.</param>
        /// <param name="active">Initial value of the active property.</param>
        public static SurveyUser CreateSurveyUser(global::System.String user_name, global::System.Boolean active)
        {
            SurveyUser surveyUser = new SurveyUser();
            surveyUser.user_name = user_name;
            surveyUser.active = active;
            return surveyUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                if (_user_name != value)
                {
                    Onuser_nameChanging(value);
                    ReportPropertyChanging("user_name");
                    _user_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("user_name");
                    Onuser_nameChanged();
                }
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private global::System.Boolean _active;
        partial void OnactiveChanging(global::System.Boolean value);
        partial void OnactiveChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SurveyEntities", Name="FindUHTenant_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class FindUHTenant_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FindUHTenant_Result object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="persNo">Initial value of the PersNo property.</param>
        /// <param name="tenure">Initial value of the Tenure property.</param>
        /// <param name="region">Initial value of the Region property.</param>
        public static FindUHTenant_Result CreateFindUHTenant_Result(global::System.String name, global::System.Int32 persNo, global::System.String tenure, global::System.String region)
        {
            FindUHTenant_Result findUHTenant_Result = new FindUHTenant_Result();
            findUHTenant_Result.Name = name;
            findUHTenant_Result.PersNo = persNo;
            findUHTenant_Result.Tenure = tenure;
            findUHTenant_Result.Region = region;
            return findUHTenant_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UHTenancyRef
        {
            get
            {
                return _UHTenancyRef;
            }
            set
            {
                OnUHTenancyRefChanging(value);
                ReportPropertyChanging("UHTenancyRef");
                _UHTenancyRef = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UHTenancyRef");
                OnUHTenancyRefChanged();
            }
        }
        private global::System.String _UHTenancyRef;
        partial void OnUHTenancyRefChanging(global::System.String value);
        partial void OnUHTenancyRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PersNo
        {
            get
            {
                return _PersNo;
            }
            set
            {
                OnPersNoChanging(value);
                ReportPropertyChanging("PersNo");
                _PersNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PersNo");
                OnPersNoChanged();
            }
        }
        private global::System.Int32 _PersNo;
        partial void OnPersNoChanging(global::System.Int32 value);
        partial void OnPersNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tenure
        {
            get
            {
                return _Tenure;
            }
            set
            {
                OnTenureChanging(value);
                ReportPropertyChanging("Tenure");
                _Tenure = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tenure");
                OnTenureChanged();
            }
        }
        private global::System.String _Tenure;
        partial void OnTenureChanging(global::System.String value);
        partial void OnTenureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="SurveyEntities", Name="SearchResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SearchResult : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SearchResult object.
        /// </summary>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static SearchResult CreateSearchResult(global::System.String text, global::System.Int32 value)
        {
            SearchResult searchResult = new SearchResult();
            searchResult.Text = text;
            searchResult.Value = value;
            return searchResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int32 _Value;
        partial void OnValueChanging(global::System.Int32 value);
        partial void OnValueChanged();

        #endregion
    }

    #endregion
    
}
